export const SIGN_UP = 'SIGN-UP'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const LOGIN = 'LOGIN'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const GET_MATCHES = 'GET_MATCHES'
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS'
export const GET_MATCHES_FAILURE = 'GET_MATCHES_FAILURE'

export const UPLOAD_RESUME = 'UPLOAD_RESUME'
export const UPLOAD_RESUME_SUCCESS = 'UPLOAD_RESUME_SUCCESS'
export const UPLOAD_RESUME_FAILURE = 'UPLOAD_RESUME_FAILURE'
